launchdarkly/observability-sdk

- .changeset/poor-trains-speak.md
- sdk/highlight-run/src/integrations/launchdarkly/index.ts
- sdk/highlight-run/src/plugins/observe.ts
Ensures the LD integration correctly reports additional `evaluation` span attributes.
See [tech spec](https://docs.google.com/document/d/1X8L0nl0wfEXAXbuq1Onju_cGcOIEHb_mw_6LEKVkhlY/edit?tab=t.0#heading=h.y41mcmkl1t79) for more details.
Local app
changeset
no
---
Related Jira issue: [OB-139: Add feature_flag.set.id and inExperiment attributes to eval span events](https://launchdarkly.atlassian.net/browse/OB-139)
> [OB-139] add new evaluation attributes reported by @launchdarkly/observability

- .changeset/ripe-deer-sneeze.md
- e2e/react-router/src/routes/root.tsx
- sdk/highlight-run/src/client/listeners/network-listener/utils/utils.ts
- sdk/highlight-run/src/client/utils/sessionStorage/highlightSession.ts
- sdk/highlight-run/src/plugins/common.ts
- sdk/highlight-run/src/sdk/record.ts
Running `@launchdarkly/observability` and `@launchdarkly/session-replay` plugins
concurrently would cause the session id to be cleared by one before the other plugin
would be able to read it. This PR fixes the behavior to make sure that the 
session is shared between the two plugins.
Loading the `@launchdarkly/session-replay` plugin and reloading the page before
the session would initialize would start a new session on the next reload as
the stored session ID would be deleted. This PR also corrects the behavior.
https://www.loom.com/share/c9de3d20c0bf4cfb85910170306241a6?from_recorder=1&focus_title=1
changeset 
no
> fix previous session not being resumed when tab is reloaded

- .github/workflows/turbo.yml
`turbo.yml` GHA currently only auto-publishes the highlight SDKs, not the launchdarkly ones.
This is a problem since they are interdependent and should be published together if there are new versions released.
`yarn changeset version` is unrelated to npm publishing (creates PR that will bump versions if changesets are detected)
but should happen first / separately for clarity.
CI
no
no
> fix JS GHA not auto-publishing LD packages

- .changeset/fair-weeks-spend.md
- .changeset/huge-squids-yawn.md
- e2e/react-router/src/routes/root.tsx
- sdk/highlight-run/src/client/otel/exporter.ts
- sdk/highlight-run/src/sdk/observe.ts
- sdk/highlight-run/src/sdk/record.ts
- sdk/highlight-run/src/sdk/util.ts
* Improve internal logging from the SDK to report warnings to the highlight project of the customer to help troubleshoot recording kill switch triggering
* Add exponential retry backoff to the OTel exporter.
local deploy
testing retries with network throttling
changesets
no
> improve console warn forwarding from highlight.run sdk

- .github/workflows/manual-publish.yml
- .github/workflows/turbo.yml
With no changesets present, manual publish would do nothing for the highlight SDKs.
Corrected behavior tested by [kicking off](https://github.com/launchdarkly/observability-sdk/actions/runs/15079659237) manual publish.
no
no
> fix manual publish step not publishing highlight.run

- .changeset/hot-days-raise.md
- sdk/highlight-run/src/__tests__/sdk.test.ts
- sdk/highlight-run/src/client/utils/storage.ts
- sdk/highlight-run/src/plugins/common.ts
- sdk/highlight-run/src/plugins/observe.ts
- sdk/highlight-run/src/plugins/record.ts
- sdk/highlight-run/src/sdk/buffer.ts
- sdk/highlight-run/src/sdk/observe.ts
- sdk/highlight-run/src/sdk/record.ts
- sdk/highlight-run/src/sdk/util.ts
Ensure that observability plugin initialization does not propagate internal errors.
Improves logging of internal SDK errors.
Adds a fallback mechanism for the localStorage lookup to fall back to in-memory storage
to prevent the plugin from failing completely in the case of out of quota.
new unit test
testing local storage logic in e2e react-router app
changeset
will update gonfalon and revert https://app.ld.catamorphic.com/projects/default/flags/observability-sdk-project-id/targeting?env=catamorphic&env=production&env=staging&selected-env=production
no
> wrap plugin initialization with try / catch to limit impact of internal errors

- .changeset/spotty-books-lick.md
- .changeset/twelve-lions-taste.md
- .github/workflows/turbo.yml
- sdk/highlight-run/src/integrations/launchdarkly/index.ts
- sdk/highlight-run/src/plugins/observe.ts
- sdk/highlight-run/src/plugins/record.ts
* ensure omitting project id does not break sdk
* report all attributes of evaluation reason
before
after
testing new attrs
changeset
no
> improve attribute reporting of sdk

- .github/workflows/turbo.yml
The `changeset/action` automatically versions, so running it twice in the same workflow causes the second instance to actually publish what should instead just be added to a PR.
> Only run changeset/actions once.

- .changeset/green-eggs-win.md
- e2e/react-router/src/ldclient.tsx
- sdk/highlight-run/src/integrations/launchdarkly/index.ts
Report the LD SDK context `member.email` when available to as the o11y identifier.
changeset
will bump gonfalon session replay sdk
no
> improve gonfalon member email reporting

- .changeset/sad-emus-turn.md
- .github/PULL_REQUEST_TEMPLATE.md
- sdk/@launchdarkly/observability-react-native/CHANGELOG.md
- sdk/@launchdarkly/observability-react-native/package.json
- sdk/@launchdarkly/observability-react-native/src/api/Options.ts
- sdk/@launchdarkly/observability-react-native/src/client/InstrumentationManager.ts
- sdk/@launchdarkly/observability-react-native/src/client/ObservabilityClient.ts
- sdk/@launchdarkly/observability-react-native/src/otel/CustomBatchSpanProcessor.test.ts
- sdk/@launchdarkly/observability-react-native/src/otel/CustomBatchSpanProcessor.ts
- sdk/@launchdarkly/observability-react-native/src/otel/DeduplicatingExporter.test.ts
- sdk/@launchdarkly/observability-react-native/src/otel/DeduplicatingExporter.ts
- sdk/@launchdarkly/observability-shared/LICENSE
- sdk/@launchdarkly/observability-shared/README.md
- sdk/@launchdarkly/observability-shared/package.json
- sdk/@launchdarkly/observability-shared/src/index.ts
- sdk/@launchdarkly/observability-shared/src/instrumentation/constants.ts
- sdk/@launchdarkly/observability-shared/src/instrumentation/propagator.ts
- sdk/@launchdarkly/observability-shared/src/instrumentation/types.ts
- sdk/@launchdarkly/observability-shared/src/instrumentation/utils.ts
- sdk/@launchdarkly/observability-shared/src/launchdarkly/urlFilters.ts
- sdk/@launchdarkly/observability-shared/tsconfig.json
- yarn.lock
* Adds `tracingOrigins` config
* Adds `urlBlocklist` config
* Improves span deduplication logic
* Improves span naming
* Adds debug logging in custom processor and exporter
* Creates an internal package for sharing code between JS client SDKs
* Drops the design question from the PR template
Local click test with debug mode enabled.
N/A - this is only updating a package that is currently in alpha.
> Add tracingOrigins and urlBlocklist to RN Observe plugin

- .changeset/hungry-items-clap.md
- e2e/react-router/src/routes/root.tsx
- sdk/highlight-run/src/api/observe.ts
- sdk/highlight-run/src/client/otel/index.ts
- sdk/highlight-run/src/sdk/LDObserve.ts
- sdk/highlight-run/src/sdk/LDRecord.ts
- sdk/highlight-run/src/sdk/observe.ts
Add `LDObserve.stop()` to allow customers to stop observability tracking
local
https://www.loom.com/share/9a5f9c8f10c04813a21bdfebb7a09439
changeset
> introduce LDObserve.stop api

- .changeset/swift-dodos-watch.md
- sdk/highlight-run/src/client/utils/sessionStorage/highlightSession.ts
- sdk/highlight-run/src/client/utils/storage.ts
Duplicate tabs would not clean up their old localStorage values, leading to issues where we would
exceed localStorage quota.
local deploy
https://www.loom.com/share/9c351101df184660a24433325f82bba4
changeset
> cleanup old sessionData_ localStorage values

- .github/workflows/manual-publish-docs.yml
- .github/workflows/turbo.yml
- scripts/package-name.sh
- sdk/@launchdarkly/observability-node/README.md
- sdk/@launchdarkly/observability-node/package.json
Adds publishing of docs for `@launchdarkly/observability-node`.
https://launchdarkly.github.io/observability-sdk/sdk/@launchdarkly/observability-node/
Automatically publishes docs on turbo repo build.
> Add docs publishing for observability-node.

- .github/workflows/manual-publish-docs.yml
- .github/workflows/publish-docs.yml
- .github/workflows/turbo.yml
Attempt to resolve concurrency group issue.
Representative build: https://github.com/launchdarkly/observability-sdk/actions/runs/16329406252
> Independent concurrency groups for monorepo build and docs.

- .changeset/spicy-rivers-search.md
- sdk/highlight-run/src/client/types/observe.ts
- sdk/highlight-run/src/client/types/record.ts
update o11y plugin docs to point to new launchdarkly pages and correctly reflect the SDK name
CI
changeset
> fix: update web o11y plugin docs

- sdk/@launchdarkly/observability-dotnet/AspSampleApp/Program.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/DefaultNames.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/ObservabilityExtensions.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/Observe.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/Otel/AttributeNames.cs
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/LaunchDarkly.Observability.Tests.csproj
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/ObserveTests.cs
Implements singleton for recording observability information for .Net.
Unit tests.
Manual testing.
> feat: Add singleton for dotnet.

- go/internal/otel/otel.go
Configure the global OTEL logger provider.
Logs coming thru with https://github.com/launchdarkly/observability/pull/151
will release new go tag
> fix(go): configure default logger provider

- sdk/@launchdarkly/observability-dotnet/.editorconfig
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/DefaultNames.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/ObservabilityConfig.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/Sampling/IExportSampler.cs
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/ObservabilityConfigBuilderTests.cs
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/SamplingConfigClientTests.cs
Add editor config and reformat files. Subsequent PR will add CI lint check.
> chore: Dotnet editor config and style.

- .github/workflows/release-please.yml
Needed to call the re-usable workflows as jobs, not as steps.
> chore: Correct reusable workflow usage for publishing docs.

- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/BaseBuilder.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/EnvironmentHelper.cs
- sdk/@launchdarkly/observability-dotnet/src/LaunchDarkly.Observability/EnvironmentVariables.cs
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/ObservabilityConfigBuilderTests.cs
- sdk/@launchdarkly/observability-dotnet/test/LaunchDarkly.Observability.Tests/ObservabilityPluginBuilderTests.cs
Add support for common OTEL environment variables.
The underlying OTEL libraries support most variables, but our default configuration would interfere with these specific ones without explicit support.
> feat: Add support for environment variable configuration.

- e2e/go-plugin/README.md
- e2e/go-plugin/cmd/preinit/preinit.go
- go/initialize.go
- go/plugin.go
Allow for initialization of Go observability independent of the LaunchDarkly SDK.
This allows for advanced use-cases where the LD SDK may not be in use, or may not be readily accessible.
I called it `PreInitialize`, but I am not attached to that name. 
You do this:
```go
// Initialize the observability plugin ahead of the LaunchDarkly client.
// This is generally only required for advanced use cases and is not the
// recommended way to initialize observability.
// Observability can also be used without the LaunchDarkly client at all
// by using this method. Some features will not be available when using
// observability without the LaunchDarkly client.
ldobserve.PreInitialize(os.Getenv("LAUNCHDARKLY_SDK_KEY"),
ldobserve.WithEnvironment("test"), …
```
> feat: Support Go observability initialization independent of plugins.

- release-please-config.json
There was some refactoring in the go SDK which moved where the version is stored. The release-please config was not updated for the change
> fix: Fix telemetry version for Go plugin.
